# cd.yml

name: CD

# Change to only run on tags in the future
on: [push]

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Build
        run: docker build . -f DtekShutdownCheckBot/Dockerfile -t dteckshutdownbot

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Log in
        run: heroku container:login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_TOKEN }}

      - name: Deploy
        run: |
          docker tag dteckshutdownbot registry.heroku.com/${{ secrets.HEROKU_APP }}/web
          docker push registry.heroku.com/${{ secrets.HEROKU_APP }}/web

      - name: Release
        run: heroku container:release web -a ${{ secrets.HEROKU_APP }}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_TOKEN }}
